server:
  port: 2223
  error:
    include-message: always
    include-binding-errors: always

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8099/eureka/
  instance:
    instance-id: ${spring.application.name}:${server.port}