server:
  port: 8080

#Conexion a Eureka Server
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8099/eureka/

#Configuracion a Gateway
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: microservice-curso
        uri: lb://microservice-curso
        predicates:
        - Path=/cursos/**