server:
  port: 2223
  error:
    include-message: always
    include-binding-errors: always

security:
  oauth2:
    resource:
      user-info-uri: http://localhost:4445/user
      
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8199/eureka/
  instance:
    instance-id: ${spring.application.name}:${server.port}