server:
 port: 6666
 
#ribbon:#  eureka:#    enabled: false

#Habilita circuitbreaker en feign para leer los fallbacks
feign:  circuitbreaker:    enabled: true
  compression:    request:      enabled: true
    response:      enabled: true

resilience4j:  circuitbreaker:    instances:      microservice-alumno:
        register-health-indicator: true
        event-consumer-buffer-size: 10
        automatic-transition-from-open-to-half-open-enabled: true
        failure-rate-threshold: 50 #Porcentaje de Tasa de fallo, si se excede se abre el circuito
        minimum-number-of-calls: 5
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-size: 10
        wait-duration-in-open-state: 5s
        sliding-window-type: count-based  timelimiter:    configs:      default:
            cancelRunningFuture: false
            timeoutDuration: 2s #Timeout
#management:#  health:#    circuitbreakers:#      enabled: true
#  endpoints:#    web:#      exposure:#        include:#        - health
#  endpoint:#    health:#      show-details: always

management:  endpoints:    web:      exposure:        include: '*'  endpoint:    health:      show-details: always